### ISSUE TITLE
Electronic Contract Administration System (ECAS) - Phase 2

### ISSUE THREAD

**Issue by bcdevex** [bcgov/EDUC-ECAS#11]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-electronic-contract-administration-system--ecas----phase-2"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-electronic-contract-administration-system--ecas----phase-2">visit the opportunity page</a>.
The opportunity closes on <b>Monday, June 10th, 2019 at 16:00 PDT</b>.</p>

**Comment by GregFPoirier** [comment]
Hi all, if there are any questions please post here I'll respond as fast as I can.

**Comment by mark-a-wilson** [comment]
Hi @GregFPoirier , 

Sorry for not spending more time with you on defining this opportunity...I'm concerned that you're going to need to define this a lot more in order for developers to understand the scope of your ask and decide whether it's worth applying for the price.

Initial observations:
1. There are no Installation/Setup/Development instructions in the [README](https://github.com/bcgov/ECAS/blob/master/README.md) — it may take a lot of effort for developers (other than the ones who have built the app so far) to get the app running in order to get an idea of what you might mean by the new features you've listed in the Acceptance Criteria.
2. The items in the Acceptance Criteria are very generic (e.g. what might be the scope of "Profile Management"?!)
3. The Acceptance Criteria states, "...but not limited to" ... this sounds like you are trying to reserve the right to expand the scope before paying the fixed price?! 

Sorry for putting this out in the open (I should have spent more time helping you out with this). My intent isn't to 'call you out' but to encourage interested developers to pipe in here to help us make appropriate revisions for a clearer opportunity. Thanks!

**Comment by GregFPoirier** [comment]
All good @mark-a-wilson, this is the first one of these so I want to make sure that we get it right as well.

If you go into the Openshift folder you'll find a readme specific to that environment.

For the MS Dynamics portion of the application there is no real installation/Setup beyond getting MS Dynamics on-premise set up.

Profile Management for phase 2 involves: 
- Creation of reports on the registered users based on the data fields input and the status's
- Adding additional fields
- Adding in email correspondence with registered users.

As for the "...but not limited to"   this is intended to provide some flexibility as the Agile process will likely come up with additional stories that the Product Owner will need to prioritize against existing stories.

**Comment by mark-a-wilson** [comment]
Thanks Greg!

On Jun 3, 2019, at 12:18 PM, Greg <notifications@github.com<mailto:notifications@github.com>> wrote:


All good @mark-a-wilson<https://github.com/mark-a-wilson>, this is the first one of these so I want to make sure that we get it right as well.

If you go into the Openshift folder you'll find a readme specific to that environment.

For the MS Dynamics portion of the application there is no real installation/Setup beyond getting MS Dynamics on-premise set up.

Profile Management for phase 2 involves:

  *   Creation of reports on the registered users based on the data fields input and the status's
  *   Adding additional fields
  *   Adding in email correspondence with registered users.

As for the "...but not limited to" this is intended to provide some flexibility as the Agile process will likely come up with additional stories that the Product Owner will need to prioritize against existing stories.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by GregFPoirier** [comment]
Thanks to those that took the time to review this opportunity.
